### ISSUE TITLE
unconditionally generate lockfile

### ISSUE THREAD

**Issue by japaric** [japaric/cross#53]
Right now, something like this produces an error:

```
$ cargo add foo
$ cross build
error: failed to write /project/Cargo.lock

Caused by:
  failed to open: /project/Cargo.lock
```

**Comment by Emilgardis** [comment]
There doesn't seem to be a way to replicate  `cargo build` when it adds new deps. Closest match is `cargo update`, but that can also update deps.

**Comment by japaric** [comment]
`cargo generate-lockfile` does the trick, I think, if you call it before `cross build`. I don't think it *updates* dependencies; it just adds new dependencies and changes their paths/git urls if necessary.

**Comment by tbu-** [comment]
Looks like this was fixed in 0.1.5.

**Comment by SirDoctors** [comment]
I'm still seeing this issue, using the latest version. Here's a log https://travis-ci.org/mgattozzi/alchemist/jobs/204565275#L524

**Comment by Emilgardis** [comment]
You should let cross do it with `cross build/run`, with `cross generate-lockfile` you are telling cargo to generate a lockfile inside the docker image.

**Comment by SirDoctors** [comment]
The error still shows up with that not there, I added it to test if it would help, I'll remove it and try again though...

**Comment by Emilgardis** [comment]
I think #67 is the cause, `cargo fetch` is run, but somehow cargo still complains. I think we need to run `cargo fetch --target <target-triple>` to make this work. Not sure.

This issue should be reopened.

**Comment by japaric** [comment]
OK. I think I found the problem. This is a workspace so `cargo fetch` is producing a `Cargo.lock` in the *root* of the workspace but when you call `cd alchemist && cross build --target $T`, Cargo tries to create a new `Cargo.lock` in *that* directory.

Using `cross build --target $T -p alchemist` from the *root* of the repository seems to at least produce / use the right `Cargo.lock` and starts the build process (then it fails to link with `/usr/bin/ld: cannot find -lsqlite3` but that's a totally different problem)

**Comment by SirDoctors** [comment]
Its looking for sqlite3 since that (for the moment) is the database we are using for alchemist. So this should be fine if we just use -p whicheverproject is getting built then?
